---
title: 'Proyecto visualización: Imagen Covid'
author: "Grupo K"
date: "2024-03-05"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Cargamos las librerías
suppressWarnings({ #Para que no salgan los warnings
  library(readr)
  library(ggplot2)
  library(plotly)
})

# Importamos la información
datos <- read.csv("owid-covid-data.csv")
```

```{r}
# Cargamos los países que tenemos que mostrar según el enunciado
us <- datos[datos$location == "United States",] 
it <- datos[datos$location == "Italy",] 
fr <- datos[datos$location == "France",]
ge <- datos[datos$location == "Germany",]
ca <- datos[datos$location == "Canada",]
ja <- datos[datos$location == "Japan",]
uk <- datos[datos$location == "United Kingdom",]
sp <- datos[datos$location == "Spain",]

# Creamos un nuevo data frame con los datos que nos interesan
# (España lo añadimos más tarde, puesto que tiene un grosor distinto)
df <- rbind(us, it, fr, ge, ca, ja, uk)

# Convertir la columna 'date' a formato de fecha
sp$date <- as.Date(sp$date, format = "%Y-%m-%d")

# Asegurarse de que la columna 'date' en el conjunto de datos df ya esté en formato de fecha
df$date <- as.Date(df$date, format = "%Y-%m-%d")

```


```{r}
# Creamos el gráfico con la información. En el eje 'x' ponemos las fechas (que
# se vea el tiempo) y en el eje 'y' las muertes por millón. Cogemos smoothed
# para que salga el gráfico más adecuado.

gr <- ggplot(df, mapping = aes(x = date, y = new_deaths_smoothed_per_million, 
                               group = location))

# Añadimos linea con color a los países, color según país (más tarde 
# añadiremos España)
gr_col <- gr + geom_line(aes(colour = location))

# Ponemos como se va a mostrar la fecha
gr_col_fecha <- gr_col + scale_x_date(date_labels = "%d %m %Y") + 
  labs(x = "",y = "")

# Ponemos el título
gr_final<- gr_col_fecha + 
  ggtitle("Daily new confirmed COVID-19 deaths per million people") + 
  
  # Añadimos España más grueso y de color rojo
  geom_line(data = sp, aes(x = date, y = new_deaths_smoothed_per_million), 
            color = "red", linewidth = 0.75) + 
  
  # Quitamos la leyenda
  theme(legend.position = "none")
```


```{r}
gr_interactivo <- ggplotly(gr_final)

# Mostrar el gráfico interactivo
gr_interactivo

```

